apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-python
  template:
    metadata:
      labels:
        app: app-python
    spec:
      containers:
        - name: app-python
          image: jmartinezfusion/app-python:d13dda
          ports:
            - containerPort: 5000
