name: Update K8s Image Tag

on:
  repository_dispatch:
    types: [update-k8s-deployment]

jobs:
  update-image-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v3

      - name: List files after checkout
        run: ls -la

      - name: Install correct yq (Go version)
        run: |
          mkdir -p $HOME/bin
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O $HOME/bin/yq
          chmod +x $HOME/bin/yq
          echo "$HOME/bin" >> $GITHUB_PATH  # agrega a $PATH

      - name: Confirm yq version
        run: yq --version

      - name: Install kubeseal
        uses: digitalservicebund/setup-kubeseal@LATEST_HASH
        with:
          version: v0.29.0

      - name: Create Kubernetes Secret
        run: |
          echo "
          apiVersion: v1
          kind: Secret
          metadata:
            name: my-secret
            namespace: demo
          type: Opaque
          data:
            username: $(echo -n 'admin' | base64)
            password: $(echo -n 's3cr3t' | base64)
          " > my-secret.yaml

      - name: Seal the secret
        run: |
          kubeseal --format yaml --cert ${{ secrets.CERT_KUBESEAL }} < my-secret.yaml > sealed-secret.yaml

      - name: View sealed secret
        run: |
          cat sealed-secrets.yaml | kubeseal --validate

      - name: Replace image tag using yq
        run: |
          TAG=${{ github.event.client_payload.image_tag }}
          yq e '.spec.template.spec.containers[0].image = "jmartinezfusion/app-python:'"$TAG"'"' -i deployment.yaml
          git diff deployment.yaml
 
      - name: View deployment.yaml
        run: cat deployment.yaml
    
      - name: Commit files
        run: |
          git config --local user.email "jmartinez@fusionglobal.tech"
          git config --local user.name "jmartinez-fusion"
          git commit -a -m "Add changes"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_PUSH }}
          branch: ${{ github.ref }}
