name: Update K8s Image Tag

on:
  repository_dispatch:
    types: [update-k8s-deployment]

jobs:
  update-image-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v3

      - name: List files after checkout
        run: ls -la

      - name: Install correct yq (Go version)
        run: |
          mkdir -p $HOME/bin
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O $HOME/bin/yq
          chmod +x $HOME/bin/yq
          echo "$HOME/bin" >> $GITHUB_PATH  # agrega a $PATH

      - name: Confirm yq version
        run: yq --version

      - name: Replace image tag using yq
        run: |
          TAG=${{ github.event.client_payload.image_tag }}
          yq e '.spec.template.spec.containers[0].image = "jmartinezfusion/app-python:'"$TAG"'"' -i deployment.yaml
          git diff deployment.yaml
 
      - name: View deployment.yaml
        run: cat deployment.yaml

      - name: Set up Git credentials
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://${{ secrets.PAT_PUSH }}@github.com/jmartinez-fusion/cicd-infra.git

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update image tag to $TAG"
          git push

